package com.example.demo.service.impl;

import com.example.demo.exception.ResourceNotFoundException;
import com.example.demo.model.StudentProfile;
import com.example.demo.repository.StudentProfileRepository;
import com.example.demo.service.StudentProfileService;
import org.springframework.stereotype.Service;
import java.util.List;

@Service
public class StudentProfileServiceImpl implements StudentProfileService {
    private final StudentProfileRepository repository;

    public StudentProfileServiceImpl(StudentProfileRepository repository) {
        this.repository = repository;
    }

    @Override
    public StudentProfile createStudent(StudentProfile profile) {
        // Fix: Use correct getter names matching updated Entity
        if (repository.existsByStudentld(profile.getStudentld()) || repository.existsByEmail(profile.getEmail())) {
            throw new IllegalArgumentException("studentld exists");
        }
        return repository.save(profile);
    }

    @Override
    public StudentProfile getStudentByld(Long id) {
        return repository.findById(id).orElseThrow(() -> new ResourceNotFoundException("not found"));
    }

    @Override
    public List<StudentProfile> getAllStudents() {
        return repository.findAll();
    }

    @Override
    public StudentProfile findByStudentld(String studentld) {
        return repository.findByStudentld(studentld).orElseThrow(() -> new ResourceNotFoundException("not found"));
    }

    @Override
    public void updateStudentStatus(Long id, boolean active) {
        StudentProfile s = getStudentByld(id);
        // Fix: Use correct setter generated by Lombok for Boolean active
        s.setActive(active); 
        repository.save(s);
    }
}